services:
  spring:
    image: order-system
    environment:
      - JAVA_OPTS=-javaagent:/dd-java-agent.jar
      - DD_SERVICE=order-system-api
      - DD_ENV=dev
      - DD_VERSION=1.0
      - DD_AGENT_HOST=host.docker.internal
      - DD_TRACE_AGENT_PORT=8126
      - DD_LOGS_INJECTION=true
      - DD_JMX=true
    volumes:
      - ./dd-java-agent.jar:/dd-java-agent.jar
    ports:
      - 8080:8080
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: order_system_db
    ports:
      - 3306:3306

