services:
  spring:
    image: order_system
    container_name: orderSystem
    ports:
      - 8080:8080
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

